### ISSUE TITLE
[HP] Backbround sous Chrome

### ISSUE THREAD

**Issue by thom4s** [Jok-Rr/alx_breuil#18]
no repeat pas pris en compte... sous Chrome. Tester les versions.

![Image 04-04-2022 à 09 16](https://user-images.githubusercontent.com/1851204/161494534-312c1cf3-1dff-4d5c-9cf2-9f78643d39f7.jpg)

**Comment by TomBost-web** [comment]
![image](https://user-images.githubusercontent.com/74453277/162701443-c846b311-7ace-4a1a-b11e-f43e817c029c.png)
Tout s'affiche également bien sur Chrome dans mon cas
