### ISSUE TITLE
[MODAL] Marges 

### ISSUE THREAD

**Issue by thom4s** [Jok-Rr/alx_breuil#19]
Vérifier marges sous Chrome dans la modal (à droite à d l'image...)
Tester versions...

![Image 04-04-2022 à 09 25](https://user-images.githubusercontent.com/1851204/161494665-815067dc-ac05-4b2e-b8af-b91773ac8533.jpg)

**Comment by TomBost-web** [comment]
Tout s'affiche bien sur Chrome pour ma pars, je développe et test sous chrome. C'est étrange..
