### ISSUE TITLE
[FILTRES] Cumul des filtres

### ISSUE THREAD

**Issue by thom4s** [Jok-Rr/alx_breuil#6]
1. Peut on bien cumuler les filtres ? Kanj'Arbres de 2021 au format 41 x 31 cm ? 
2. Il faut un style du coup sur les 2 filtres activés

**Comment by TomBost-web** [comment]
Je pense que l'on peut mais au vu du nombre d'œuvre je pense que un filtre suffit, après c'est mon avis a voir avec Alexandre. Par contre c'est un peut vague pour mettre en place plusieurs filtre d'un coup

**Comment by thom4s** [comment]
ok. On laisse comme ça et on voit avec Alex.

**Comment by thom4s** [comment]
pas de cumul de filtres.
